### ISSUE TITLE
Provide isEmailValid function

### ISSUE THREAD

**Issue by mikehedman** [hoodiehq/hapi-account#5]
Since many of the new methods are dependent on email, it'll be important that we get a good email address from the user.  Since all apps will need to ask the user for an email address, I think it would be good to provide a default email input validation function.  

Here's a function I use:

```js
function(email) {
  //this regex pulled from http://www.regular-expressions.info/email.html
  if (!/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/.test(email)) {
    return 'Invalid email address.';
  }
}
```

One could argue that this could/should be done "isomorphically", that is, available on the client side, but also enforced on the server side.

**Comment by mikehedman** [comment]
This could be a "version 2" thing.

**Comment by gr2m** [comment]
What I'd suggest is to use the plugin (or here: hoodie-account-server) configuration for this: https://github.com/hoodiehq/hoodie-account-server/tree/api#configuring-the-server

In`options.schema`, you could set `"format":"email"` for username, or require a separate `"email"` property, that has `"type":"string", "format": "email"`.

Ideally the schema configurations would be bundled into the front-end API, so when you try to sign up with an invalid email, but ``"format":"email"`` is set on username, it'd fail directly without even sending a request to the server.

Would that work for this use case?

**Comment by mikehedman** [comment]
I think this might be a spot where trying to describe in English is harder than in code :)   That is, I suspect I will agree with you once the implementation gets roughed out in code, but I don't completely visualize how what you are saying would be implemented, so I can't jump in with a "Yeah, exactly!!" ;)

**Comment by gr2m** [comment]
I guess this is covered now with https://github.com/hoodiehq/hapi-account/tree/master/client#accountvalidate ? Validation is app-specific, for example some apps require a valid email address as username, others allow to optionally add an email address.

```js
errors = account.validate({username: 'john@example.com'})
errors = account.validate({profile: {email: 'john@example.com'}})

// also check if username is still available?
account.validate({username: 'john@example.com'})
.then(function () { /* all good */ } )
.catch(function (errors) { /* handle errors */ } )
```

**Comment by mikehedman** [comment]
Works for me.
