### ISSUE TITLE
Provide a re-send confirmation email api

### ISSUE THREAD

**Issue by mikehedman** [hoodiehq/hapi-account#6]
I'm thinking of a use case where the user has signed up (but not confirmed), tries to signin and is told that they need to confirm their account by means of the email that they received.  They check their mail and because of some circumstance (went to spam and was purged) the mail is not available.

This could definitely be deferred to version 2, though I suspect it would be pretty quick to implement once the main confirmation flow is built.

**Comment by gr2m** [comment]
great use case! For the discussion at https://github.com/hoodiehq/hoodie-account-server/pull/1, we don't need to differentiate between what version this should land, let's postpone that discussion for later. Everything we agree on that should go into the new hoodie account core module, we should add it there, to make sure it won't break in future.

Once we agree on APIs, we can split up the work into different steps, and agree on a initial feature set that we definitely need, and then enhancements for later, which will be great things the community could contribute to, as they won't be critical for the upcoming Hoodie release
